apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: api
          image: kandit/product-ms:0.3
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: product
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product
  namespace: default
  annotations:
    konghq.com/methods: "GET,POST"

spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /v1/product
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80
